spring.application.name=modile-banking-aba


#
spring.datasource.url=jdbc:postgresql://localhost:4000/aft_mobile_banking
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=RongRong0903

# create-drop: Create and then destroy the schema at the end of the session

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true